# Wire up travis
language: python

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -e .[testing]
  - pip install flake8

# command to run tests
script:
  - flake8 .
  - pytest --cov=trousse

after_success:
  - coveralls
  
notifications:
  slack:
    secure: scXDWD8UAsSDwSIeHdpoh4iK7R8DvkSEZOc+WAieKC6Dz+TYOEt08JOU6uiaKaqZAGHn/Zkp3balELRRXeap3HBfqNH1Tm2De+DLFDEdiQRDLnOlT/I4jzTl4Unof+QMeVtz6f5+lVKMTBozz4D6YXnWIFZONMCKTHTzhLnDPa8hRHFUfKHZGSW3wM2FWYjObNOew1+6SLkq3h7L5UCYgvf6ubbhW9/1N9nOAMs4YZZt3ND12bzq1L/D381W94VrpsR2O1rwcMwfqW+cJbb9++UPY8/PhmjvRuM42Q5YdE+EGgNW2IR57pA4XNxzCtOIZEKBFlPki+IFUwOKBK5yTK4oUPBnB8OrTiIcgD1aOle+cXWKuG24GqKa/wOaIsYri1EG3pkq+yE86EWoImwB0PDYzr+AOYt8ujZzodbTvCCSp0IjonwQZqu/ot1rgXgQDPHgrg2Uoo59cyaVXVCflQOjr6W0kyOlIe9wWH0mzq+WphZU+ZjUJLNMUIh2XJ1qR2npPk3ZmiLqS4DX/DcdzRjD5Vi9EjLc6zFb1OPfAu8CMBnpGKT4DUQi0AxaLDgYdmeTEYQrXloh7bpHidpd+ZFZtPbMkkjHiw8spSJ/RCLRy02TOZEkGgWi14iXZkim1323E8KMKvv2oMB0UU00xd6ZRaFc852/bXjGJ8gZRXU=
